### ISSUE TITLE
錄youtube直播出現錯誤

### ISSUE THREAD

**Issue by brina60602** [GiGaFotress/Vtuber-recorder#9]
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 7, in <module>
    from streamlink_cli.main import main
  File "/usr/local/lib/python3.6/site-packages/streamlink_cli/main.py", line 21, in <module>
    import streamlink.logger as logger
  File "/usr/local/lib/python3.6/site-packages/streamlink/__init__.py", line 19, in <module>
    from streamlink.api import streams
  File "/usr/local/lib/python3.6/site-packages/streamlink/api.py", line 1, in <module>
    from streamlink.session import Streamlink
  File "/usr/local/lib/python3.6/site-packages/streamlink/session.py", line 16, in <module>
    from streamlink.plugin.api.http_session import HTTPSession
  File "/usr/local/lib/python3.6/site-packages/streamlink/plugin/api/__init__.py", line 1, in <module>
    from streamlink.plugin.api.http_session import HTTPSession
  File "/usr/local/lib/python3.6/site-packages/streamlink/plugin/api/http_session.py", line 13, in <module>
    from streamlink.utils.parse import parse_json, parse_xml
  File "/usr/local/lib/python3.6/site-packages/streamlink/utils/__init__.py", line 1, in <module>
    from streamlink.utils.cache import LRUCache
  File "/usr/local/lib/python3.6/site-packages/streamlink/utils/cache.py", line 2, in <module>
    from typing import Generic, Optional, OrderedDict as TOrderedDict, TypeVar
ImportError: cannot import name 'OrderedDict'

**Comment by brina60602** [comment]
重新安装后又可以录了
